### ISSUE TITLE
PCB - JLCPCB

### ISSUE THREAD

**Issue by smrtnt** [KULeuven-COSIC/Starlink-FI#1]
Hi @LennertW,
Thanks for sharing these great resources. 

I have just ordered a few PCBs from JLCPCB and they came back to me regarding some connections.

> As shown below, the trace indicated at arrow are disconnected, shall we connect them to proceed?

[Screenshot](https://share.icloud.com/photos/0f5OY1T_wpi77sUh1J5hEBoYA)

I assume they should be connected.

Thanks in advance,
Sam

**Comment by LennertW** [comment]
Hi Sam!

That's odd, I did not receive that question while ordering!
These are definitely connected in the top plane through vias. Having them connected in the bottom plane definitely won't hurt.
I will update that in the design files soon, thanks for letting me know.

**Comment by SamZorSec** [comment]
Hi @LennertW,
Thanks for the reply. Looking forward to your updated design ;-). Thanks

**Comment by LennertW** [comment]
The current design should be good to go as is, it is what I used!
Might take some time before I get around to updating it here, no reason to wait for that ;)
